spring:
  application:
    name: gateway
  profiles:
    active: docker
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  cloud:
    config:
      name: gateway
server:
  port: 8080
